version: "3.3"

services:
  efb:
    image: ghcr.io/jiz4oh/efb
    container_name: efb
    network_mode: host
    volumes:
      - .:/data
    restart: unless-stopped
    environment:
      - EFB_PROFILE=comwechat
    logging:
      driver: json-file
      options:
        max-size: 1m
    depends_on:
      - comwechat
      - comwechat2

  comwechat:
    container_name: comwechat
    environment:
        - VNCPASS=jiz4oh
        - COMWECHAT=https://github.com/ljc545w/ComWeChatRobot/releases/download/3.7.0.30-0.1.0-pre/3.7.0.30-0.1.0-pre.zip
    volumes:
        - "./profiles/comwechat/honus.comwechat/WeChat/Files/:/home/user/.wine/drive_c/users/user/My Documents/WeChat Files/"
        - "./profiles/comwechat/honus.comwechat/WeChat/Data/:/home/user/.wine/drive_c/users/user/Application Data/"
        - "./comwechat.py:/comwechat.py"
    privileged: true
    ports:
      - 5905:5905
      - 18888:18888
    image: tomsnow1999/docker-com_wechat_robot:latest
